version : 2
jobs :
  build: 
    docker :
      - image: circleci/python:3.7
   # working_directory: ~/repo
    steps:
      - checkout
      - run :
          name: login DockerHub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker --version
      - run: docker swarm init
      - run: sleep 90
      - run: docker service ps bitroid_app
      - run: docker service ls
      - run: docker ps -a
      - run :
          name: buil images and push to DockerHub
          command: |
            docker build --tag=baihaki/appcircleci .
            docker push baihaki/appcircleci:${CIRCLE_SHA1}


