version : 2
jobs :
  build: 
    docker :
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run :
          name: login DockerHub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            sudo systemctl start docker
            sudo systemctl enable docker
            docker run -d --name db baihaki/hellodocker:ujiversion
            docker images
      
      - run :
          name: buil images and push to DockerHub
          command: |
            docker build --tag=baihaki/appcircleci .
            docker push baihaki/appcircleci:${CIRCLE_SHA1}


