
version: 2
jobs:
 build:
   docker:
     - image: circleci/python:3.7
   steps:
     - checkout
     - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
     
     - run: 
         name : Docker Login and cek images
         command : |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag=baihaki/appcircleci:$TAG .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  
          docker push baihaki/appcircleci:$TAG 
