
version: 2
jobs:
 build:
   docker:
   - image: circleci/python:3.7
   steps:
     - checkout
     - run: 
         name : Docker Login and cek images
         command : |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
     - run: 
          name: buil images and push to DockerHub
          command: |
            sudo docker build --tag=baihaki/appcircleci .
            sudo docker push baihaki/appcircleci:${CIRCLE_SHA1}
